# Seeding B cells dictionary

#VRC01GL_FRWH1_nt   = "CAGGTGCAGCTGGTGCAGTCTGGGGCTGAGGTGAAGAAGCCTGGGGCCTCAGTGAAGGTCTCCTGCAAGGCTTCTGGATACACCTTC"
#VRC01GL_CDRH1_nt   = "ACCGGCTACTATATGCAC"
#VRC01GL_FRWH2_nt   = "TGGGTGCGACAGGCCCCTGGACAAGGGCTTGAGTGGATGGGA"
#VRC01GL_CDRH2_nt   = "TGGATCAACCCTAACAGTGGTGGCACAAACTATGCACAGAAGTTTCAGGGC"
#VRC01GL_FRWH3_nt   = "AGGGTCACCATGACCAGGGACACGTCCATC------------AGCACAGCCTACATGGAGCTGAGCAGGCTGAGATCTGACGACACGGCCGTGTATTACTGTGCGAGA"
#VRC01GL_CDRH3_nt   = "GGAAAAAACTGT---------GAT---TACAATTGGGACTTCCAGCACTGGGGCCAGGGCACCCTGGTCACC"
#VRC01GL_FRWL1_nt   = "GTGTTGACACAGTCTCCAGCCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGC"
#VRC01GL_CDRL1_nt   = "AGGGCCAGTCAGAGTGTTAGCAGCTACTTAGCC"
#VRC01GL_FRWL2_nt   = "TGGTACCAACAGAAACCTGGCCAGGCTCCCAGGCTCCTCATCTAT"
#VRC01GL_CDRL2_nt   = "GATGCATCCAACAGGGCCACT"
#VRC01GL_FRWL3_nt   = "GGCATCCCAGCCAGGTTCAGTGGCAGTGGGTCTGGGACAGACTTCACTCTCACCATCAGCAGCCTAGAGCCTGAAGATTTTGCAGTTTATTACTGT"
#VRC01GL_CDRL3_nt   = "CAGCAGTATGAATTTTTTGGCCAGGGGACCAAG------TTAGAA"
#
#NIH4546GL_FRWH1_nt = "CAGGTGCAGCTGGTGCAGTCTGGGGCTGAGGTGAAGAAGCCTGGGGCCTCAGTGAAGGTCTCCTGCAAGGCTTCTGGATACACCTTC"
#NIH4546GL_CDRH1_nt = "ACCGGCTACTATATGCAC"
#NIH4546GL_FRWH2_nt = "TGGGTGCGACAGGCCCCTGGACAAGGGCTTGAGTGGATGGGA"
#NIH4546GL_CDRH2_nt = "TGGATCAACCCTAACAGTGGTGGCACAAACTATGCACAGAAGTTTCAGGGC"
#NIH4546GL_FRWH3_nt = "AGGGTCACCATGACCAGGGACACGTCCATC------------AGCACAGCCTACATGGAGCTGAGCAGGCTGAGATCTGACGACACGGCCGTGTATTACTGTGCGAGA"
#NIH4546GL_CDRH3_nt = "GGAAAATATTGTACTGCGCGCGATTATTACAATTGGGACTTCCAGCACTGGGGCCAGGGCACCCTGGTCACC"
#NIH4546GL_FRWL1_nt = "GTGTTGACACAGTCTCCAGCCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGC"
#NIH4546GL_CDRL1_nt = "AGGGCCAGTCAGAGTGTTAGCAGCTACTTAGCC"
#NIH4546GL_FRWL2_nt = "TGGTACCAACAGAAACCTGGCCAGGCTCCCAGGCTCCTCATCTAT"
#NIH4546GL_CDRL2_nt = "GATGCATCCAACAGGGCCACT"
#NIH4546GL_FRWL3_nt = "GGCATCCCAGCCAGGTTCAGTGGCAGTGGGTCTGGGACAGACTTCACTCTCACCATCAGCAGCCTAGAGCCTGAAGATTTTGCAGTTTATTACTGT"
#NIH4546GL_CDRL3_nt = "CAGCAGTATGAATTTTTTGGCCAGGGGACCAAG------TTAGAA"
#
#BNC60GL_FRWH1_nt   = "CAGGTGCAGCTGGTGCAGTCTGGGGCTGAGGTGAAGAAGCCTGGGGCCTCAGTGAAGGTCTCCTGCAAGGCTTCTGGATACACCTTC"
#BNC60GL_CDRH1_nt   = "ACCGGCTACTATATGCAC"
#BNC60GL_FRWH2_nt   = "TGGGTGCGACAGGCCCCTGGACAAGGGCTTGAGTGGATGGGA"
#BNC60GL_CDRH2_nt   = "TGGATCAACCCTAACAGTGGTGGCACAAACTATGCACAGAAGTTTCAGGGC"
#BNC60GL_FRWH3_nt   = "AGGGTCACCATGACCAGGGACACGTCCATC------------AGCACAGCCTACATGGAGCTGAGCAGGCTGAGATCTGACGACACGGCCGTGTATTACTGTGCGAGA"
#BNC60GL_CDRH3_nt   = "GAACGCAGCGAC---------------TTT---TGGGACTTCGATCTGTGGGGCAGGGGCACCCTGGTCACC"
#BNC60GL_FRWL1_nt   = "CAGATGACACAGTCTCCATCCTCCCTGTCTGCATCTGTAGGGGATAGAGTCACCATCACTTGC"
#BNC60GL_CDRL1_nt   = "CAGGCCAGTCAGGATATCAGCAACTACTTAAAT"
#BNC60GL_FRWL2_nt   = "TGGTACCAACAGAAACCTGGCAAAGCTCCCAAACTCCTCATCTAT"
#BNC60GL_CDRL2_nt   = "GATGCATCCAACTTGGAGACT"
#BNC60GL_FRWL3_nt   = "GGCGTCCCATCAAGGTTCAGTGGCAGTGGGTCTGGGACAGACTTCACTTTCACCATCAGCAGCCTACAGCCTGAAGATATAGCAACATATTACTGT"
#BNC60GL_CDRL3_nt   = "CAGCAGTATGAATTTATCGGCCCTGGGACCAAG------TTAAAA"

VRC01GL_FRWH1_nt   = "CAGGTGCAGCTGGTGCAGTCTGGGGCTGAGGTGAAGAAGCCTGGGGCCTCAGTGAAGGTCTCCTGCAAGGCTTCTGGATACACCTTC"
VRC01GL_CDRH1_nt   = "ACCGGCTACTATATGCAC"
VRC01GL_FRWH2_nt   = "TGGGTGCGACAGGCCCCTGGACAAGGGCTTGAGTGGATGGGA"
VRC01GL_CDRH2_nt   = "TGGATCAACCCTAACAGTGGTGGCACAAACTATGCACAGAAGTTTCAGGGC"
VRC01GL_FRWH3_nt   = "AGGGTCACCATGACCAGGGACACGTCCATCAGCACAGCCTACATGGAGCTGAGCAGGCTGAGATCTGACGACACGGCCGTGTATTACTGTGCGAGA"
VRC01GL_CDRH3_nt   = "GGAAAAAACTGTGATTACAATTGGGACTTCCAGCACTGGGGCCAGGGCACCCTGGTCACC"
VRC01GL_FRWL1_nt   = "GTGTTGACACAGTCTCCAGCCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGC"
VRC01GL_CDRL1_nt   = "AGGGCCAGTCAGAGTGTTAGCAGCTACTTAGCC"
VRC01GL_FRWL2_nt   = "TGGTACCAACAGAAACCTGGCCAGGCTCCCAGGCTCCTCATCTAT"
VRC01GL_CDRL2_nt   = "GATGCATCCAACAGGGCCACT"
VRC01GL_FRWL3_nt   = "GGCATCCCAGCCAGGTTCAGTGGCAGTGGGTCTGGGACAGACTTCACTCTCACCATCAGCAGCCTAGAGCCTGAAGATTTTGCAGTTTATTACTGT"
VRC01GL_CDRL3_nt   = "CAGCAGTATGAATTTTTTGGCCAGGGGACCAAGTTAGAA"

NIH4546GL_FRWH1_nt = "CAGGTGCAGCTGGTGCAGTCTGGGGCTGAGGTGAAGAAGCCTGGGGCCTCAGTGAAGGTCTCCTGCAAGGCTTCTGGATACACCTTC"
NIH4546GL_CDRH1_nt = "ACCGGCTACTATATGCAC"
NIH4546GL_FRWH2_nt = "TGGGTGCGACAGGCCCCTGGACAAGGGCTTGAGTGGATGGGA"
NIH4546GL_CDRH2_nt = "TGGATCAACCCTAACAGTGGTGGCACAAACTATGCACAGAAGTTTCAGGGC"
NIH4546GL_FRWH3_nt = "AGGGTCACCATGACCAGGGACACGTCCATCAGCACAGCCTACATGGAGCTGAGCAGGCTGAGATCTGACGACACGGCCGTGTATTACTGTGCGAGA"
NIH4546GL_CDRH3_nt = "GGAAAATATTGTACTGCGCGCGATTATTACAATTGGGACTTCCAGCACTGGGGCCAGGGCACCCTGGTCACC"
NIH4546GL_FRWL1_nt = "GTGTTGACACAGTCTCCAGCCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGC"
NIH4546GL_CDRL1_nt = "AGGGCCAGTCAGAGTGTTAGCAGCTACTTAGCC"
NIH4546GL_FRWL2_nt = "TGGTACCAACAGAAACCTGGCCAGGCTCCCAGGCTCCTCATCTAT"
NIH4546GL_CDRL2_nt = "GATGCATCCAACAGGGCCACT"
NIH4546GL_FRWL3_nt = "GGCATCCCAGCCAGGTTCAGTGGCAGTGGGTCTGGGACAGACTTCACTCTCACCATCAGCAGCCTAGAGCCTGAAGATTTTGCAGTTTATTACTGT"
NIH4546GL_CDRL3_nt = "CAGCAGTATGAATTTTTTGGCCAGGGGACCAAGTTAGAA"

BNC60GL_FRWH1_nt   = "CAGGTGCAGCTGGTGCAGTCTGGGGCTGAGGTGAAGAAGCCTGGGGCCTCAGTGAAGGTCTCCTGCAAGGCTTCTGGATACACCTTC"
BNC60GL_CDRH1_nt   = "ACCGGCTACTATATGCAC"
BNC60GL_FRWH2_nt   = "TGGGTGCGACAGGCCCCTGGACAAGGGCTTGAGTGGATGGGA"
BNC60GL_CDRH2_nt   = "TGGATCAACCCTAACAGTGGTGGCACAAACTATGCACAGAAGTTTCAGGGC"
BNC60GL_FRWH3_nt   = "AGGGTCACCATGACCAGGGACACGTCCATCAGCACAGCCTACATGGAGCTGAGCAGGCTGAGATCTGACGACACGGCCGTGTATTACTGTGCGAGA"
BNC60GL_CDRH3_nt   = "GAACGCAGCGACTTTTGGGACTTCGATCTGTGGGGCAGGGGCACCCTGGTCACC"
BNC60GL_FRWL1_nt   = "CAGATGACACAGTCTCCATCCTCCCTGTCTGCATCTGTAGGGGATAGAGTCACCATCACTTGC"
BNC60GL_CDRL1_nt   = "CAGGCCAGTCAGGATATCAGCAACTACTTAAAT"
BNC60GL_FRWL2_nt   = "TGGTACCAACAGAAACCTGGCAAAGCTCCCAAACTCCTCATCTAT"
BNC60GL_CDRL2_nt   = "GATGCATCCAACTTGGAGACT"
BNC60GL_FRWL3_nt   = "GGCGTCCCATCAAGGTTCAGTGGCAGTGGGTCTGGGACAGACTTCACTTTCACCATCAGCAGCCTACAGCCTGAAGATATAGCAACATATTACTGT"
BNC60GL_CDRL3_nt   = "CAGCAGTATGAATTTATCGGCCCTGGGACCAAGTTAAAA"

VRC01GL_nt   = [[ VRC01GL_FRWH1_nt, VRC01GL_CDRH1_nt, VRC01GL_FRWH2_nt, VRC01GL_CDRH2_nt, VRC01GL_FRWH3_nt, VRC01GL_CDRH3_nt ], 
                [ VRC01GL_FRWL1_nt, VRC01GL_CDRL1_nt, VRC01GL_FRWL2_nt, VRC01GL_CDRL2_nt, VRC01GL_FRWL3_nt, VRC01GL_CDRL3_nt ]]

NIH4546GL_nt = [[ NIH4546GL_FRWH1_nt, NIH4546GL_CDRH1_nt, NIH4546GL_FRWH2_nt, NIH4546GL_CDRH2_nt, NIH4546GL_FRWH3_nt, NIH4546GL_CDRH3_nt ], 
                [ NIH4546GL_FRWL1_nt, NIH4546GL_CDRL1_nt, NIH4546GL_FRWL2_nt, NIH4546GL_CDRL2_nt, NIH4546GL_FRWL3_nt, NIH4546GL_CDRL3_nt ]]

BNC60GL_nt   = [[ BNC60GL_FRWH1_nt, BNC60GL_CDRH1_nt, BNC60GL_FRWH2_nt, BNC60GL_CDRH2_nt, BNC60GL_FRWH3_nt, BNC60GL_CDRH3_nt ], 
                [ BNC60GL_FRWL1_nt, BNC60GL_CDRL1_nt, BNC60GL_FRWL2_nt, BNC60GL_CDRL2_nt, BNC60GL_FRWL3_nt, BNC60GL_CDRL3_nt ]]

VRC01GL_nt_str   = ''.join(str(r) for v in VRC01GL_nt for r in v)
NIH4546GL_nt_str = ''.join(str(r) for v in NIH4546GL_nt for r in v)
BNC60GL_nt_str   = ''.join(str(r) for v in BNC60GL_nt for r in v)

seedingCells=[]
seedingCells.append(VRC01GL_nt_str)
#seedingCells.append(NIH4546GL_nt_str)
#seedingCells.append(BNC60GL_nt_str)

lenFRWH1=len(VRC01GL_nt[0][0])
lenCDRH1=len(VRC01GL_nt[0][1])
lenFRWH2=len(VRC01GL_nt[0][2])
lenCDRH2=len(VRC01GL_nt[0][3])
lenFRWH3=len(VRC01GL_nt[0][4])
lenCDRH3=len(VRC01GL_nt[0][5])
lenFRWL1=len(VRC01GL_nt[1][0])
lenCDRL1=len(VRC01GL_nt[1][1])
lenFRWL2=len(VRC01GL_nt[1][2])
lenCDRL2=len(VRC01GL_nt[1][3])
lenFRWL3=len(VRC01GL_nt[1][4])
lenCDRL3=len(VRC01GL_nt[1][5])

print(seedingCells)
#print(lenFRWH1,lenCDRH1,lenFRWH2,lenCDRH2,lenFRWH3,lenCDRH3,lenFRWL1,lenCDRL1,lenFRWL2,lenCDRL2,lenFRWL3,lenCDRL3)
